// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fneodcbgymdeksuynpuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZW9kY2JneW1kZWtzdXlucHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDIyNDYsImV4cCI6MjA2NzAxODI0Nn0.54hzm9uL71Fendno3NeoXDyWl19b37HVmg62j8v90QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});